import Dexie, { type Table } from "dexie";

// =========================
// Core entity records
// =========================

export interface AkunRecord {
    id: string;
    nama: string;
    tipe: string; // BANK | E_WALLET | CASH | CREDIT_CARD | EXPENSE | INCOME
    saldoAwalInt: number;
    saldoSekarangInt: number;
    limitKreditInt?: number | null;
    setoranAwalInt?: number | null;
    minPaymentFixedInt?: number | null;
    minInstallmentAmountInt?: number | null;
    templateId?: string | null;
    templateSource?: string | null;
    templateOverrides?: string | null;
    icon?: string | null;
    warna?: string | null;
    isSyariah?: boolean | null;
    billingDate?: number | null;
    dueDate?: number | null;
    minPaymentPercent?: number | null;
    useDecimalFormat?: boolean;
    biayaAdminAktif?: boolean;
    biayaAdminNominalInt?: number | null;
    biayaAdminPola?: string | null;
    biayaAdminTanggal?: number | null;
    bungaAktif?: boolean;
    bungaTiers?: string | null;
    lastAdminChargeDate?: Date | null;
    lastInterestCreditDate?: Date | null;
    settingsLastModified?: Date | null;
    createdAt: Date;
    updatedAt: Date;
}

export interface TransaksiRecord {
    id: string;
    tanggal: Date;
    deskripsi: string;
    nominalInt: number;
    kategori: string;
    debitAkunId: string;
    kreditAkunId: string;
    rencanaCicilanId?: string | null;
    convertedToInstallment?: boolean;
    catatan?: string | null;
    idempotencyKey?: string | null;
    createdAt: Date;
}

export interface RencanaCicilanRecord {
    id: string;
    namaProduk: string;
    totalPokokInt: number;
    tenor: number;
    cicilanKe: number;
    nominalPerBulanInt: number;
    biayaAdminInt?: number | null;
    bungaPersen?: number | null;
    tanggalJatuhTempo: number;
    status: string; // AKTIF | LUNAS | DIBALIKKAN
    akunKreditId: string;
    akunDebitId: string;
    isConvertedFromTx?: boolean;
    originalTxId?: string | null;
    templateId?: string | null;
    adminFeeType?: string | null;
    adminFeeAmount?: number | null;
    installmentType?: string | null;
    createdAt: Date;
    updatedAt: Date;
}

export interface RecurringTransactionRecord {
    id: string;
    nama: string;
    nominalInt: number;
    kategori: string;
    tipeTransaksi: string; // KELUAR | MASUK
    akunId: string;
    frekuensi: string; // HARIAN | MINGGUAN | BULANAN | TAHUNAN
    hariDalamBulan?: number | null;
    hariDalamMinggu?: number | null;
    tanggalMulai: Date;
    tanggalSelesai?: Date | null;
    aktif: boolean;
    terakhirDieksekusi?: Date | null;
    isAutoGenerated?: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface BudgetRecord {
    id: string;
    kategori: string;
    bulan: number;
    tahun: number;
    nominal: number;
    createdAt: Date;
    updatedAt: Date;
}

export interface NetWorthSnapshotRecord {
    id: string;
    tanggal: Date;
    totalAset: number;
    totalHutang: number;
    netWorth: number;
    breakdown?: string | null; // JSON
    createdAt?: Date;
}

export interface CurrencyRateRecord {
    id: string;
    kodeAsal: string;
    kodeTujuan: string;
    rate: number;
    tanggalUpdate: Date;
    sumber?: string | null;
    createdAt: Date;
    updatedAt: Date;
}

export interface AppSettingRecord {
    id: string;
    kunci: string;
    nilai: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface AdminFeeRecord {
    id: string;
    akunId: string;
    deskripsi: string;
    nominal: number;
    recurringTxId?: string | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface InstallmentTemplateRecord {
    id: string;
    nama: string;
    bankName: string;
    cardType: string;
    tenorOptions: string; // JSON
    adminFeeType: string;
    adminFeeAmount?: number | null;
    interestRate: number;
    notes?: string | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface NotificationRecord {
    id: string;
    type: string;
    title: string;
    message: string;
    severity: string; // INFO | WARNING | ERROR
    read: boolean;
    actionUrl?: string | null;
    createdAt: Date;
    updatedAt: Date;
}

export interface FilterPresetRecord {
    id: string;
    name: string;
    icon?: string | null;
    filters: string; // JSON
    usageCount: number;
    createdAt: Date;
    updatedAt: Date;
}

export interface AccountTemplateRecord {
    id: string;
    nama: string;
    tipeAkun: string;
    biayaAdmin?: number | null;
    bungaTier?: string | null;
    polaTagihan: string;
    tanggalTagihan?: number | null;
    deskripsi?: string | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface TemplateTransaksiRecord {
    id: string;
    nama: string;
    deskripsi: string;
    nominal: number;
    kategori: string;
    tipeTransaksi: string;
    akunId: string;
    icon?: string | null;
    warna?: string | null;
    usageCount: number;
    createdAt: Date;
    updatedAt: Date;
}

export interface LogSistemRecord {
    id: string;
    level: string;
    modul: string;
    pesan: string;
    stackTrace?: string | null;
    createdAt: Date;
}

export interface KategoriRecord {
    id: string;
    nama: string;
    parentId?: string | null;  // null = kategori utama
    icon: string;              // lucide icon name
    warna: string;             // hex color
    nature: string;            // MUST | NEED | WANT
    show: boolean;             // visibility toggle
    order: number;             // untuk sorting
    createdAt: Date;
    updatedAt: Date;
}

// =========================
// Analytics summary records
// =========================

export interface SummaryMonthRecord {
    id: string; // YYYY-MM
    month: string; // YYYY-MM
    totalIn: number;
    totalOut: number;
    net: number;
    txCount: number;
}

export interface SummaryCategoryMonthRecord {
    id: string; // YYYY-MM|kategori
    month: string;
    kategori: string;
    totalOut: number;
    txCount: number;
}

export interface SummaryHeatmapDayRecord {
    id: string; // YYYY-MM-DD
    tanggal: string; // YYYY-MM-DD
    totalOut: number;
    txCount: number;
}

export interface SummaryAccountMonthRecord {
    id: string; // YYYY-MM|akunId
    month: string;
    akunId: string;
    delta: number;
    txCount: number;
}

// =========================
// Archive metadata
// =========================

export interface ArchivePeriodRecord {
    id: string; // YYYY-MM
    archived: boolean;
    archiveFileRef?: string | null;
    createdAt: Date;
}

// =========================
// Dexie DB
// =========================

export class DompetkuDB extends Dexie {
    akun!: Table<AkunRecord, string>;
    transaksi!: Table<TransaksiRecord, string>;
    rencanaCicilan!: Table<RencanaCicilanRecord, string>;
    recurringTransaction!: Table<RecurringTransactionRecord, string>;
    budget!: Table<BudgetRecord, string>;
    netWorthSnapshot!: Table<NetWorthSnapshotRecord, string>;
    currencyRate!: Table<CurrencyRateRecord, string>;
    appSetting!: Table<AppSettingRecord, string>;
    adminFee!: Table<AdminFeeRecord, string>;
    installmentTemplate!: Table<InstallmentTemplateRecord, string>;
    notification!: Table<NotificationRecord, string>;
    filterPreset!: Table<FilterPresetRecord, string>;
    accountTemplate!: Table<AccountTemplateRecord, string>;
    templateTransaksi!: Table<TemplateTransaksiRecord, string>;
    logSistem!: Table<LogSistemRecord, string>;
    kategori!: Table<KategoriRecord, string>;

    summaryMonth!: Table<SummaryMonthRecord, string>;
    summaryCategoryMonth!: Table<SummaryCategoryMonthRecord, string>;
    summaryHeatmapDay!: Table<SummaryHeatmapDayRecord, string>;
    summaryAccountMonth!: Table<SummaryAccountMonthRecord, string>;
    archivePeriod!: Table<ArchivePeriodRecord, string>;

    constructor() {
        super("dompetku");

        this.version(1).stores({
            akun: "id, nama, tipe, createdAt, updatedAt",
            transaksi: "id, tanggal, kategori, debitAkunId, kreditAkunId, rencanaCicilanId, idempotencyKey, [tanggal+id], [kategori+tanggal], [debitAkunId+tanggal], [kreditAkunId+tanggal]",
            rencanaCicilan: "id, status, tanggalJatuhTempo, akunKreditId, akunDebitId, createdAt",
            recurringTransaction: "id, akunId, frekuensi, aktif, terakhirDieksekusi, createdAt",
            budget: "id, kategori, [bulan+tahun]",
            netWorthSnapshot: "id, tanggal",
            currencyRate: "id, [kodeAsal+kodeTujuan], tanggalUpdate",
            appSetting: "id, kunci, updatedAt",
            adminFee: "id, akunId, isActive, recurringTxId",
            installmentTemplate: "id, bankName, isActive",
            notification: "id, read, createdAt",
            filterPreset: "id, name, usageCount",
            accountTemplate: "id, nama, tipeAkun, isActive",
            templateTransaksi: "id, nama, kategori, tipeTransaksi, akunId",
            logSistem: "id, level, modul, createdAt",

            summaryMonth: "id, month",
            summaryCategoryMonth: "id, month, kategori",
            summaryHeatmapDay: "id, tanggal",
            summaryAccountMonth: "id, month, akunId",
            archivePeriod: "id, archived, createdAt",
        });

        this.version(2).stores({
            akun: "id, nama, tipe, createdAt, updatedAt",
            transaksi: "id, tanggal, kategori, debitAkunId, kreditAkunId, rencanaCicilanId, idempotencyKey, [tanggal+id], [kategori+tanggal], [debitAkunId+tanggal], [kreditAkunId+tanggal]",
            rencanaCicilan: "id, status, tanggalJatuhTempo, akunKreditId, akunDebitId, createdAt",
            recurringTransaction: "id, akunId, frekuensi, terakhirDieksekusi, createdAt",
            budget: "id, kategori, [bulan+tahun]",
            netWorthSnapshot: "id, tanggal",
            currencyRate: "id, [kodeAsal+kodeTujuan], tanggalUpdate",
            appSetting: "id, kunci, updatedAt",
            adminFee: "id, akunId, isActive, recurringTxId",
            installmentTemplate: "id, bankName, isActive",
            notification: "id, read, createdAt",
            filterPreset: "id, name, usageCount",
            accountTemplate: "id, nama, tipeAkun, isActive",
            templateTransaksi: "id, nama, kategori, tipeTransaksi, akunId",
            logSistem: "id, level, modul, createdAt",

            summaryMonth: "id, month",
            summaryCategoryMonth: "id, month, kategori",
            summaryHeatmapDay: "id, tanggal",
            summaryAccountMonth: "id, month, akunId",
            archivePeriod: "id, archived, createdAt",
        });

        // Version 3: Add missing indexes for aktif and biayaAdminAktif
        this.version(3).stores({
            akun: "id, nama, tipe, biayaAdminAktif, createdAt, updatedAt",
            transaksi: "id, tanggal, kategori, debitAkunId, kreditAkunId, rencanaCicilanId, idempotencyKey, [tanggal+id], [kategori+tanggal], [debitAkunId+tanggal], [kreditAkunId+tanggal]",
            rencanaCicilan: "id, status, tanggalJatuhTempo, akunKreditId, akunDebitId, createdAt",
            recurringTransaction: "id, akunId, frekuensi, aktif, terakhirDieksekusi, createdAt",
            budget: "id, kategori, [bulan+tahun]",
            netWorthSnapshot: "id, tanggal",
            currencyRate: "id, [kodeAsal+kodeTujuan], tanggalUpdate",
            appSetting: "id, kunci, updatedAt",
            adminFee: "id, akunId, isActive, recurringTxId",
            installmentTemplate: "id, bankName, isActive",
            notification: "id, read, createdAt",
            filterPreset: "id, name, usageCount",
            accountTemplate: "id, nama, tipeAkun, isActive",
            templateTransaksi: "id, nama, kategori, tipeTransaksi, akunId, usageCount",
            logSistem: "id, level, modul, createdAt",

            summaryMonth: "id, month",
            summaryCategoryMonth: "id, month, kategori",
            summaryHeatmapDay: "id, tanggal",
            summaryAccountMonth: "id, month, akunId",
            archivePeriod: "id, archived, createdAt",
        });

        // Version 4: Add kategori table for hierarchical categories
        this.version(4).stores({
            akun: "id, nama, tipe, biayaAdminAktif, createdAt, updatedAt",
            transaksi: "id, tanggal, kategori, debitAkunId, kreditAkunId, rencanaCicilanId, idempotencyKey, [tanggal+id], [kategori+tanggal], [debitAkunId+tanggal], [kreditAkunId+tanggal]",
            rencanaCicilan: "id, status, tanggalJatuhTempo, akunKreditId, akunDebitId, createdAt",
            recurringTransaction: "id, akunId, frekuensi, aktif, terakhirDieksekusi, createdAt",
            budget: "id, kategori, [bulan+tahun]",
            netWorthSnapshot: "id, tanggal",
            currencyRate: "id, [kodeAsal+kodeTujuan], tanggalUpdate",
            appSetting: "id, kunci, updatedAt",
            adminFee: "id, akunId, isActive, recurringTxId",
            installmentTemplate: "id, bankName, isActive",
            notification: "id, read, createdAt",
            filterPreset: "id, name, usageCount",
            accountTemplate: "id, nama, tipeAkun, isActive",
            templateTransaksi: "id, nama, kategori, tipeTransaksi, akunId, usageCount",
            logSistem: "id, level, modul, createdAt",
            kategori: "id, nama, parentId, nature, show, order, createdAt",

            summaryMonth: "id, month",
            summaryCategoryMonth: "id, month, kategori",
            summaryHeatmapDay: "id, tanggal",
            summaryAccountMonth: "id, month, akunId",
            archivePeriod: "id, archived, createdAt",
        });

        // Version 5: Add nominalInt index to transaksi table
        this.version(5).stores({
            akun: "id, nama, tipe, biayaAdminAktif, createdAt, updatedAt",
            transaksi: "id, tanggal, kategori, nominalInt, debitAkunId, kreditAkunId, rencanaCicilanId, idempotencyKey, [tanggal+id], [kategori+tanggal], [debitAkunId+tanggal], [kreditAkunId+tanggal]",
            rencanaCicilan: "id, status, tanggalJatuhTempo, akunKreditId, akunDebitId, createdAt",
            recurringTransaction: "id, akunId, frekuensi, aktif, terakhirDieksekusi, createdAt",
            budget: "id, kategori, [bulan+tahun]",
            netWorthSnapshot: "id, tanggal",
            currencyRate: "id, [kodeAsal+kodeTujuan], tanggalUpdate",
            appSetting: "id, kunci, updatedAt",
            adminFee: "id, akunId, isActive, recurringTxId",
            installmentTemplate: "id, bankName, isActive",
            notification: "id, read, createdAt",
            filterPreset: "id, name, usageCount",
            accountTemplate: "id, nama, tipeAkun, isActive",
            templateTransaksi: "id, nama, kategori, tipeTransaksi, akunId, usageCount",
            logSistem: "id, level, modul, createdAt",
            kategori: "id, nama, parentId, nature, show, order, createdAt",

            summaryMonth: "id, month",
            summaryCategoryMonth: "id, month, kategori",
            summaryHeatmapDay: "id, tanggal",
            summaryAccountMonth: "id, month, akunId",
            archivePeriod: "id, archived, createdAt",
        });
    }
}

export const db = new DompetkuDB();

