-- AlterTable
ALTER TABLE "akun" ADD COLUMN "billingDate" INTEGER;
ALTER TABLE "akun" ADD COLUMN "dueDate" INTEGER;
ALTER TABLE "akun" ADD COLUMN "isSyariah" BOOLEAN;
ALTER TABLE "akun" ADD COLUMN "minInstallmentAmount" REAL;
ALTER TABLE "akun" ADD COLUMN "minPaymentFixed" REAL;
ALTER TABLE "akun" ADD COLUMN "minPaymentPercent" REAL DEFAULT 5;

-- CreateTable
CREATE TABLE "admin_fee" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "akunId" TEXT NOT NULL,
    "deskripsi" TEXT NOT NULL,
    "nominal" REAL NOT NULL,
    "recurringTxId" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "admin_fee_akunId_fkey" FOREIGN KEY ("akunId") REFERENCES "akun" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "admin_fee_recurringTxId_fkey" FOREIGN KEY ("recurringTxId") REFERENCES "recurring_transaction" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "installment_template" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "nama" TEXT NOT NULL,
    "bankName" TEXT NOT NULL,
    "cardType" TEXT NOT NULL,
    "tenorOptions" TEXT NOT NULL,
    "adminFeeType" TEXT NOT NULL,
    "adminFeeAmount" REAL,
    "interestRate" REAL NOT NULL DEFAULT 0,
    "notes" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_recurring_transaction" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "nama" TEXT NOT NULL,
    "nominal" REAL NOT NULL,
    "kategori" TEXT NOT NULL,
    "tipeTransaksi" TEXT NOT NULL,
    "akunId" TEXT NOT NULL,
    "frekuensi" TEXT NOT NULL,
    "hariDalamBulan" INTEGER,
    "hariDalamMinggu" INTEGER,
    "tanggalMulai" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tanggalSelesai" DATETIME,
    "aktif" BOOLEAN NOT NULL DEFAULT true,
    "terakhirDieksekusi" DATETIME,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_recurring_transaction" ("aktif", "akunId", "createdAt", "frekuensi", "hariDalamBulan", "hariDalamMinggu", "id", "kategori", "nama", "nominal", "tanggalMulai", "tanggalSelesai", "terakhirDieksekusi", "tipeTransaksi", "updatedAt") SELECT "aktif", "akunId", "createdAt", "frekuensi", "hariDalamBulan", "hariDalamMinggu", "id", "kategori", "nama", "nominal", "tanggalMulai", "tanggalSelesai", "terakhirDieksekusi", "tipeTransaksi", "updatedAt" FROM "recurring_transaction";
DROP TABLE "recurring_transaction";
ALTER TABLE "new_recurring_transaction" RENAME TO "recurring_transaction";
CREATE TABLE "new_transaksi" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tanggal" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deskripsi" TEXT NOT NULL,
    "nominal" REAL NOT NULL,
    "kategori" TEXT NOT NULL,
    "debitAkunId" TEXT NOT NULL,
    "kreditAkunId" TEXT NOT NULL,
    "rencanaCicilanId" TEXT,
    "convertedToInstallment" BOOLEAN NOT NULL DEFAULT false,
    "idempotencyKey" TEXT,
    "catatan" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "transaksi_debitAkunId_fkey" FOREIGN KEY ("debitAkunId") REFERENCES "akun" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "transaksi_kreditAkunId_fkey" FOREIGN KEY ("kreditAkunId") REFERENCES "akun" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "transaksi_rencanaCicilanId_fkey" FOREIGN KEY ("rencanaCicilanId") REFERENCES "rencana_cicilan" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_transaksi" ("catatan", "createdAt", "debitAkunId", "deskripsi", "id", "idempotencyKey", "kategori", "kreditAkunId", "nominal", "rencanaCicilanId", "tanggal") SELECT "catatan", "createdAt", "debitAkunId", "deskripsi", "id", "idempotencyKey", "kategori", "kreditAkunId", "nominal", "rencanaCicilanId", "tanggal" FROM "transaksi";
DROP TABLE "transaksi";
ALTER TABLE "new_transaksi" RENAME TO "transaksi";
CREATE UNIQUE INDEX "transaksi_idempotencyKey_key" ON "transaksi"("idempotencyKey");
CREATE INDEX "transaksi_tanggal_id_idx" ON "transaksi"("tanggal", "id");
CREATE INDEX "transaksi_kategori_idx" ON "transaksi"("kategori");
CREATE INDEX "transaksi_debitAkunId_tanggal_idx" ON "transaksi"("debitAkunId", "tanggal");
CREATE INDEX "transaksi_kreditAkunId_tanggal_idx" ON "transaksi"("kreditAkunId", "tanggal");
CREATE TABLE "new_rencana_cicilan" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "namaProduk" TEXT NOT NULL,
    "totalPokok" REAL NOT NULL,
    "tenor" INTEGER NOT NULL,
    "cicilanKe" INTEGER NOT NULL DEFAULT 1,
    "nominalPerBulan" REAL NOT NULL,
    "biayaAdmin" REAL NOT NULL DEFAULT 0,
    "bungaPersen" REAL NOT NULL DEFAULT 0,
    "tanggalJatuhTempo" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'AKTIF',
    "akunKreditId" TEXT NOT NULL,
    "akunDebitId" TEXT NOT NULL,
    "isConvertedFromTx" BOOLEAN NOT NULL DEFAULT false,
    "originalTxId" TEXT,
    "templateId" TEXT,
    "adminFeeType" TEXT,
    "adminFeeAmount" REAL,
    "installmentType" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "rencana_cicilan_originalTxId_fkey" FOREIGN KEY ("originalTxId") REFERENCES "transaksi" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "rencana_cicilan_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "installment_template" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_rencana_cicilan" ("akunDebitId", "akunKreditId", "biayaAdmin", "bungaPersen", "cicilanKe", "createdAt", "id", "namaProduk", "nominalPerBulan", "status", "tanggalJatuhTempo", "tenor", "totalPokok", "updatedAt") SELECT "akunDebitId", "akunKreditId", "biayaAdmin", "bungaPersen", "cicilanKe", "createdAt", "id", "namaProduk", "nominalPerBulan", "status", "tanggalJatuhTempo", "tenor", "totalPokok", "updatedAt" FROM "rencana_cicilan";
DROP TABLE "rencana_cicilan";
ALTER TABLE "new_rencana_cicilan" RENAME TO "rencana_cicilan";
CREATE UNIQUE INDEX "rencana_cicilan_originalTxId_key" ON "rencana_cicilan"("originalTxId");
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;

-- CreateIndex
CREATE UNIQUE INDEX "admin_fee_recurringTxId_key" ON "admin_fee"("recurringTxId");
