"use server"

import prisma from "@/lib/prisma"
import { logSistem } from "@/lib/logger"
import { revalidatePath } from "next/cache"

/**
 * Create admin fee with auto-generated recurring transaction
 */
export async function createAdminFee(
    akunId: string,
    deskripsi: string,
    nominal: number
) {
    try {
        // Validate inputs
        if (!akunId || !deskripsi || nominal <= 0) {
            return { success: false, error: "Data tidak valid" }
        }

        // Get account details
        const akun = await prisma.akun.findUnique({
            where: { id: akunId }
        })

        if (!akun) {
            return { success: false, error: "Akun tidak ditemukan" }
        }

        // Use Prisma transaction for atomicity
        const result = await prisma.$transaction(async (tx) => {
            // 1. Create recurring transaction first
            const recurringTx = await tx.recurringTransaction.create({
                data: {
                    nama: `[Auto] ${deskripsi}`,
                    nominal: nominal,
                    kategori: "Biaya Admin",
                    tipeTransaksi: "KELUAR",
                    akunId: akunId,
                    frekuensi: "BULANAN",
                    hariDalamBulan: 1, // Default: tanggal 1
                    aktif: true,
                    isAutoGenerated: true
                }
            })

            // 2. Create admin fee linked to recurring
            const adminFee = await tx.adminFee.create({
                data: {
                    akunId: akunId,
                    deskripsi: deskripsi,
                    nominal: nominal,
                    recurringTxId: recurringTx.id,
                    isActive: true
                }
            })

            return { adminFee, recurringTx }
        })

        await logSistem("INFO", "ADMIN_FEE",
            `Admin fee dibuat: ${deskripsi} (Rp ${nominal.toLocaleString('id-ID')}) untuk ${akun.nama}`)

        revalidatePath("/akun")
        revalidatePath(`/akun/${akunId}`)
        revalidatePath("/recurring")

        return {
            success: true,
            data: result.adminFee,
            message: `Admin fee "${deskripsi}" berhasil dibuat dengan recurring transaction`
        }
    } catch (error) {
        await logSistem("ERROR", "ADMIN_FEE", "Gagal membuat admin fee", (error as Error).stack)
        return { success: false, error: "Gagal membuat admin fee" }
    }
}

/**
 * Update admin fee and its linked recurring transaction
 */
export async function updateAdminFee(
    id: string,
    deskripsi: string,
    nominal: number
) {
    try {
        if (!id || !deskripsi || nominal <= 0) {
            return { success: false, error: "Data tidak valid" }
        }

        // Get existing admin fee
        const existing = await prisma.adminFee.findUnique({
            where: { id },
            include: { recurringTx: true, akun: true }
        })

        if (!existing) {
            return { success: false, error: "Admin fee tidak ditemukan" }
        }

        // Use transaction for atomicity
        await prisma.$transaction(async (tx) => {
            // 1. Update admin fee
            await tx.adminFee.update({
                where: { id },
                data: {
                    deskripsi,
                    nominal,
                    updatedAt: new Date()
                }
            })

            // 2. Update linked recurring transaction if exists
            if (existing.recurringTxId) {
                await tx.recurringTransaction.update({
                    where: { id: existing.recurringTxId },
                    data: {
                        nama: `[Auto] ${deskripsi}`,
                        nominal,
                        updatedAt: new Date()
                    }
                })
            }
        })

        await logSistem("INFO", "ADMIN_FEE",
            `Admin fee diperbarui: ${deskripsi} untuk ${existing.akun.nama}`)

        revalidatePath("/akun")
        revalidatePath(`/akun/${existing.akunId}`)
        revalidatePath("/recurring")

        return { success: true, message: "Admin fee berhasil diperbarui" }
    } catch (error) {
        await logSistem("ERROR", "ADMIN_FEE", "Gagal memperbarui admin fee", (error as Error).stack)
        return { success: false, error: "Gagal memperbarui admin fee" }
    }
}

/**
 * Delete admin fee (cascade deletes recurring transaction)
 */
export async function deleteAdminFee(id: string) {
    try {
        // Get existing admin fee
        const existing = await prisma.adminFee.findUnique({
            where: { id },
            include: { recurringTx: true, akun: true }
        })

        if (!existing) {
            return { success: false, error: "Admin fee tidak ditemukan" }
        }

        // Use transaction for atomicity
        await prisma.$transaction(async (tx) => {
            // 1. Delete recurring transaction first (if exists)
            if (existing.recurringTxId) {
                await tx.recurringTransaction.delete({
                    where: { id: existing.recurringTxId }
                })
            }

            // 2. Update Akun to disable admin fee settings (Legacy sync)
            await tx.akun.update({
                where: { id: existing.akunId },
                data: {
                    biayaAdminAktif: false,
                    biayaAdminNominal: null,
                    biayaAdminPola: null,
                    biayaAdminTanggal: null
                }
            })

            // 3. Delete admin fee
            await tx.adminFee.delete({
                where: { id }
            })
        })

        await logSistem("INFO", "ADMIN_FEE",
            `Admin fee dihapus: ${existing.deskripsi} dari ${existing.akun.nama}`)

        revalidatePath("/akun")
        revalidatePath(`/akun/${existing.akunId}`)
        revalidatePath("/recurring")

        return { success: true, message: "Admin fee berhasil dihapus" }
    } catch (error) {
        await logSistem("ERROR", "ADMIN_FEE", "Gagal menghapus admin fee", (error as Error).stack)
        return { success: false, error: "Gagal menghapus admin fee" }
    }
}

/**
 * Get all admin fees for an account
 */
export async function getAdminFeesByAkun(akunId: string) {
    try {
        const adminFees = await prisma.adminFee.findMany({
            where: { akunId },
            include: {
                recurringTx: true
            },
            orderBy: { createdAt: "desc" }
        })

        return { success: true, data: adminFees }
    } catch (error) {
        await logSistem("ERROR", "ADMIN_FEE", "Gagal mengambil admin fees", (error as Error).stack)
        return { success: false, data: [], error: "Gagal mengambil admin fees" }
    }
}

/**
 * Toggle admin fee active status
 */
export async function toggleAdminFee(id: string, isActive: boolean) {
    try {
        const existing = await prisma.adminFee.findUnique({
            where: { id },
            include: { recurringTx: true, akun: true }
        })

        if (!existing) {
            return { success: false, error: "Admin fee tidak ditemukan" }
        }

        await prisma.$transaction(async (tx) => {
            // Update admin fee status
            await tx.adminFee.update({
                where: { id },
                data: { isActive }
            })

            // Update recurring transaction status
            if (existing.recurringTxId) {
                await tx.recurringTransaction.update({
                    where: { id: existing.recurringTxId },
                    data: { aktif: isActive }
                })
            }
        })

        await logSistem("INFO", "ADMIN_FEE",
            `Admin fee ${isActive ? 'diaktifkan' : 'dinonaktifkan'}: ${existing.deskripsi}`)

        revalidatePath("/akun")
        revalidatePath(`/akun/${existing.akunId}`)
        revalidatePath("/recurring")

        return { success: true }
    } catch (error) {
        await logSistem("ERROR", "ADMIN_FEE", "Gagal toggle admin fee", (error as Error).stack)
        return { success: false, error: "Gagal mengubah status admin fee" }
    }
}
